# Uncomment the next line to define a global platform for your project
#source 'https://github.com/CocoaPods/Specs.git'
# platform :ios, '9.0'
target 'noise_system' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for noise_system
  pod 'FSCalendar'
  pod ‘Alamofire’
end
